services:
  - type: web
    name: figma-mcp-server
    runtime: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:http
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: figma-mcp-server
          property: port
      - key: FIGMA_API_KEY
        sync: false
      - key: FIGMA_OAUTH_TOKEN
        sync: false
    healthCheckPath: /health 